global using System.Text.Json.Serialization;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.AspNetCore.Mvc;
global using Application;
global using Infrastructure;
global using Infrastructure.Persistence;
global using Api.Middlewares;
global using JsonOptions = Microsoft.AspNetCore.Http.Json.JsonOptions;
global using System.Net;
global using MediatR;